package compiler

import (
	"github.com/florianwoelki/reflow/ast"
	"github.com/florianwoelki/reflow/code"
	"github.com/florianwoelki/reflow/object"
)

type Compiler struct {
	instructions code.Instructions // Will hold the generated bytecode.
	constants    []object.Object   // Serves as the constant pool.
}

func New() *Compiler {
	return &Compiler{
		instructions: code.Instructions{},
		constants:    []object.Object{},
	}
}

func (c *Compiler) Compile(node ast.Node) error {
	return nil
}

func (c *Compiler) Bytecode() *Bytecode {
	return &Bytecode{
		Instructions: c.instructions,
		Constants:    c.constants,
	}
}

type Bytecode struct {
	Instructions code.Instructions
	Constants    []object.Object
}
